### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by thomastuts** [thomastuts/dissect#3]
- [ ] Add error handling
- [ ] Add more metadata
- [ ] Decide which attributes to keep (`rel`, for example?)

Got any feature requests? Add a comment in this issue!

**Comment by Krigan112** [comment]
It could be interesting that the library could crawl the images in the content of an article ( or the image that we can see when the article is shared on facebook for example ) ;)
